version: 5.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  RETAILCRM_URL:
    secure: +XvDVl4qowEEYYTdURDytjGjtBPeyehSzCqQs4XcavM=
  RETAILCRM_KEY:
    secure: xRC/iy3F1W4PCS1V1eiruJv4Sdj4A9Ln2s36fp0MtgiiIdGDHeK+Qmlm+eHAZgjh
  RETAILCRM_SITE:
    secure: 2w6OVirZRJLlkzME0kpXzQ==
  RETAILCRM_STORE:
    secure: UCnYSIgosQyIqtVwDrVv4w==
  RETAILCRM_USER:
    secure: tClF7XYbv+nGE5WpZIF7ng==
before_build:
- ps: nuget restore
build:
  verbosity: minimal